import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/header";
import { Toaster } from "react-hot-toast";
import { LanguageProvider } from "@/context/LanguageContext";
import { Footer } from '@/components/shared/footer';
import { CartProvider } from "@/context/CartContext";
const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Coffee | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
  <body className={nunito.className}>
    <LanguageProvider>
      <CartProvider>
         <main className="min-h-screen flex flex-col justify-between">
          <div>
            <Header />
            {children}
          </div>
           <Footer />
          <Toaster position="top-right" reverseOrder={false} />
        </main>
      </CartProvider>
    </LanguageProvider>
  </body>
</html>

  );
}
